const actionTypes = {
  bookTypes: {
    FETCH_BOOKS_START: 'FETCH_BOOKS_START',
    FETCH_BOOKS_SUCCESS: 'FETCH_BOOKS_SUCCESS',
    FETCH_BOOKS_FAIL: 'FETCH_BOOKS_FAIL',
    FETCH_BOOK_START: 'FETCH_BOOK_START',
    FETCH_BOOK_SUCCESS: 'FETCH_BOOK_SUCCESS',
    FETCH_BOOK_FAIL: 'FETCH_BOOK_FAIL',
    ADD_BOOK: 'ADD_BOOK',
    DELETE_BOOK: 'DELETE_BOOK',
  },
  categoryTypes: {
    FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAIL: 'FETCH_CATEGORIES_FAIL',
  },
};
export default actionTypes;
